Repository wuseal/JsonToKotlinClass, pull requests merged in 2021-07, with the labels that each got.

#366 Support adding `Expose` Annotation for Gson by new Extension
  build.gradle.kts
  src/main/kotlin/extensions/Extension.kt
  src/main/kotlin/extensions/ExtensionsCollector.kt
  src/main/kotlin/extensions/wu/seal/AddGsonExposeAnnotation.kt
  src/main/kotlin/wu/seal/jsontokotlin/ui/UIDSLV2.kt
  src/test/kotlin/extensions/wu/seal/AddGsonExposeAnnotationTest.kt
Labels: feature request

#368 🐛 fix JsonSchema type error when refer to non-object definitions
  src/main/kotlin/wu/seal/jsontokotlin/utils/classgenerator/DataClassGeneratorByJSONSchema.kt
  src/test/kotlin/wu/seal/jsontokotlin/JsonSchemaGeneratorTest.kt
  src/test/kotlin/wu/seal/jsontokotlin/TestIssue329.kt
Labels: bug

#370 Optimize Extensions' UI
  src/main/kotlin/extensions/ExtensionsCollector.kt
  src/main/kotlin/extensions/jose/han/ParcelableAnnotationSupport.kt
  src/main/kotlin/extensions/nstd/ReplaceConstructorParametersByMemberVariablesSupport.kt
  src/main/kotlin/extensions/wu/seal/AddGsonExposeAnnotationSupport.kt
  src/main/kotlin/extensions/yuan/varenyzc/BuildFromJsonObjectSupport.kt
  src/main/kotlin/extensions/yuan/varenyzc/CamelCaseSupport.kt
  src/main/kotlin/extensions/yuan/varenyzc/NeedNonNullableClassesSupport.kt
  src/test/kotlin/extensions/wu/seal/AddGsonExposeAnnotationTest.kt
Labels: enhancement

#371 Text config always loss in Adavnced --> Extension Tab
  src/main/kotlin/wu/seal/jsontokotlin/ui/UIDSLV2.kt
Labels: bug fix
